{{- if not .Values.generator.git.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.generator.git.secretName }}
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
type: Opaque
stringData:
  repo-url: {{ required "generator.git.repoUrl is required" .Values.generator.git.repoUrl | quote }}
  token: {{ required "generator.git.token is required" .Values.generator.git.token | quote }}
{{- end }}
{{- if and (not .Values.newrelic.apiKey.existingSecret) (.Values.newrelic.apiKey.value) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "phoenix.newrelic.secretName" . }}
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.newrelic.apiKey.key }}: {{ .Values.newrelic.apiKey.value | quote }}
{{- end }}