# Development patches
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      containers:
      - name: api-gateway
        env:
        - name: CORS_ALLOWED_ORIGINS
          value: "http://localhost:3000,http://localhost:5173"
        - name: LOG_FORMAT
          value: "text"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: experiment-controller
spec:
  template:
    spec:
      containers:
      - name: controller
        env:
        - name: DB_SSL_MODE
          value: "disable"
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: http
    nodePort: 30080