version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: phoenix-postgres-dev
    environment:
      POSTGRES_USER: phoenix
      POSTGRES_PASSWORD: phoenix-dev
      POSTGRES_DB: phoenix
    ports:
      - "5432:5432"
    volumes:
      - phoenix-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U phoenix"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: phoenix-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - phoenix-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: phoenix-prometheus-dev
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - phoenix-prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    container_name: phoenix-grafana-dev
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=phoenix-dev
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - phoenix-grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus

volumes:
  phoenix-postgres-data:
  phoenix-redis-data:
  phoenix-prometheus-data:
  phoenix-grafana-data:
