apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phoenix-dev

bases:
  - ../../base

namePrefix: dev-

replicas:
  - name: api-gateway
    count: 1
  - name: config-generator
    count: 1

patchesStrategicMerge:
  - patches.yaml

configMapGenerator:
  - name: phoenix-config
    behavior: merge
    literals:
      - log-level=debug
      - enable-auth=false
      - enable-profiling=true

secretGenerator:
  - name: phoenix-secrets
    behavior: replace
    literals:
      - jwt-secret=dev-secret-not-for-production
  - name: phoenix-db-credentials
    behavior: replace
    literals:
      - username=phoenix
      - password=phoenix-dev
      - database=phoenix_dev

images:
  - name: phoenix/api-gateway
    newTag: dev
  - name: phoenix/experiment-controller
    newTag: dev
  - name: phoenix/config-generator
    newTag: dev
  - name: phoenix/pipeline-operator
    newTag: dev
  - name: phoenix/loadsim-operator
    newTag: dev
  - name: phoenix/dashboard
    newTag: dev