apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcol-main
  labels:
    app: otelcol-main
    component: collector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otelcol-main
  template:
    metadata:
      labels:
        app: otelcol-main
        component: collector
    spec:
      serviceAccountName: phoenix-collector
      containers:
      - name: otelcol
        image: otel/opentelemetry-collector-contrib:0.103.1
        command: ["--config=/etc/otelcol/config.yaml"]
        ports:
        - containerPort: 4317
          name: otlp-grpc
          protocol: TCP
        - containerPort: 4318
          name: otlp-http
          protocol: TCP
        - containerPort: 8888
          name: metrics-full
          protocol: TCP
        - containerPort: 8889
          name: metrics-opt
          protocol: TCP
        - containerPort: 8890
          name: metrics-exp
          protocol: TCP
        - containerPort: 13133
          name: health
          protocol: TCP
        env:
        - name: GOMAXPROCS
          value: "2"
        - name: GOMEMLIMIT
          value: "1024MiB"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: config
          mountPath: /etc/otelcol/config.yaml
          subPath: main-collector.yaml
          readOnly: true
        - name: control-config
          mountPath: /etc/otelcol/control
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /
            port: 13133
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 13133
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: phoenix-config
      - name: control-config
        configMap:
          name: phoenix-control-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      hostNetwork: false
      dnsPolicy: ClusterFirst