receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
      memory:
      load:
      disk:
      filesystem:
      network:

processors:
  batch:

exporters:
  otlphttp/full:
    endpoint: https://otlp.nr-data.net/v1/metrics
    headers:
      api-key: ${NR_FULL_KEY}
  
  prometheus:
    endpoint: 0.0.0.0:8887
  
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8887
  
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [otlphttp/full, prometheus, prometheusremotewrite]