apiVersion: v2
name: phoenix
description: Phoenix Adaptive Cardinality Optimization System for OpenTelemetry
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - opentelemetry
  - observability
  - cardinality
  - optimization
home: https://github.com/deepaucksharma/Phoenix
sources:
  - https://github.com/deepaucksharma/Phoenix
maintainers:
  - name: Phoenix Team
    email: phoenix@example.com
dependencies:
  - name: prometheus
    version: "~25.0.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: "~7.0.0"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled