# Phoenix Platform Go Linting Configuration
# This enforces coding standards and modular boundaries
version: v1.57.0

run:
  timeout: 5m
  modules-download-mode: readonly
  build-tags:
    - integration
    - e2e
  skip-dirs:
    - vendor
    - third_party
    - testdata
    - build
    - dist

linters:
  enable:
    # Code Quality
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gosec
    - goconst
    - misspell
    
    # Complexity
    - gocyclo
    - gocognit
    - dupl
    
    # Style
    - gocritic
    - revive
    - unconvert
    
    # Dependencies
    - depguard
    
    # Error handling
    - errorlint
    - wrapcheck

linters-settings:
  gocyclo:
    min-complexity: 15
    
  gocognit:
    min-complexity: 20
    
  dupl:
    threshold: 100
    
  goconst:
    min-len: 3
    min-occurrences: 3
    
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: "Use stdlib errors with fmt.Errorf() instead"
          - pkg: "io/ioutil"
            desc: "Use io or os package instead"
        files:
          - "$all"
          - "!$test"
      
      test:
        files:
          - "$test"
        allow:
          - "$gostd"
          - "github.com/stretchr/testify"
          - "github.com/golang/mock"
          
  revive:
    rules:
      - name: package-comments
      - name: exported
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      
  errorlint:
    errorf: true
    asserts: true
    comparison: true
    
  wrapcheck:
    ignoreSigs:
      - ".Errorf("
      - "errors.New("
      - "errors.Unwrap("
      - "errors.Join("

issues:
  exclude-rules:
    # Exclude test files from some linters
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
        
    # Exclude generated files
    - path: "(.+)generated(.+)"
      linters:
        - golint
        - stylecheck
        - gosec
        
    # Exclude CRD files
    - path: api/v1
      linters:
        - gocyclo
        
  max-issues-per-linter: 50
  max-same-issues: 10
  
  # Don't report issues in vendor
  exclude-dirs:
    - vendor
    - third_party

# Severity rules for different types of issues
severity:
  default-severity: warning
  rules:
    - linters:
        - gosec
      severity: error
    - linters:
        - depguard
      severity: error