# YAML linting rules for Phoenix Platform

extends: default

rules:
  # Line length
  line-length:
    max: 120
    level: warning
    
  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true
    
  # Braces and brackets
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
    
  # Comments
  comments:
    min-spaces-from-content: 1
    
  # Truthy values
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    
  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0

# Ignore patterns
ignore: |
  vendor/
  node_modules/
  .git/
  *.generated.yaml
  *.generated.yml