apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-operator
  labels:
    app.kubernetes.io/name: pipeline-operator
    app.kubernetes.io/part-of: phoenix-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: pipeline-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pipeline-operator
    spec:
      containers:
      - name: pipeline-operator
        image: ghcr.io/phoenix/pipeline-operator:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: ENVIRONMENT
          value: production
        livenessProbe:
          httpGet:
            path: /health
            port: http
        readinessProbe:
          httpGet:
            path: /ready
            port: http
