apiVersion: v1
kind: Service
metadata:
  name: {{ include "phoenix.fullname" . }}-api
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.api.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.api.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "phoenix.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api