apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "phoenix.fullname" . }}-api
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
data:
  config.yaml: |
    server:
      grpc:
        port: 5050
        maxConnectionAge: 5m
      http:
        port: 8080
        readTimeout: 30s
        writeTimeout: 30s
      metrics:
        port: 9090
        path: /metrics
    
    database:
      maxOpenConns: 25
      maxIdleConns: 5
      connMaxLifetime: 5m
    
    auth:
      tokenExpiry: 24h
      refreshExpiry: 7d
    
    eventBus:
      bufferSize: 1000
      workers: 10
    
    experiments:
      defaultTimeout: 24h
      maxDuration: 7d
      reconcileInterval: 1m
    
    telemetry:
      serviceName: phoenix-api
      exportInterval: 10s
      sampling:
        probability: 0.1