{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "phoenix.fullname" . }}-api
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "phoenix.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from dashboard
    - from:
        - podSelector:
            matchLabels:
              {{- include "phoenix.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: dashboard
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 5050
    
    # Allow traffic from other Phoenix services
    - from:
        - podSelector:
            matchLabels:
              {{- include "phoenix.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 5050
    
    # Allow metrics scraping
    - from:
        - namespaceSelector:
            matchLabels:
              name: prometheus
      ports:
        - protocol: TCP
          port: 9090
    
    # Allow ingress traffic
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
  
  egress:
    # Allow DNS
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
    
    # Allow PostgreSQL
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql
      ports:
        - protocol: TCP
          port: 5432
    
    # Allow New Relic
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
    
    # Allow communication with other Phoenix services
    - to:
        - podSelector:
            matchLabels:
              {{- include "phoenix.selectorLabels" . | nindent 14 }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "phoenix.fullname" . }}-dashboard
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "phoenix.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: dashboard
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow ingress traffic
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 80
  
  egress:
    # Allow DNS
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
    
    # Allow API access
    - to:
        - podSelector:
            matchLabels:
              {{- include "phoenix.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: api
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 5050
{{- end }}