{{- if .Values.monitoring.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "phoenix.fullname" . }}
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
    {{- with .Values.monitoring.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: phoenix.api
      interval: 30s
      rules:
        - alert: PhoenixAPIDown
          expr: up{job="phoenix-api"} == 0
          for: 5m
          labels:
            severity: critical
            component: api
          annotations:
            summary: "Phoenix API is down"
            description: "Phoenix API has been down for more than 5 minutes."
        
        - alert: PhoenixAPIHighLatency
          expr: histogram_quantile(0.99, rate(http_request_duration_seconds_bucket{job="phoenix-api"}[5m])) > 1
          for: 10m
          labels:
            severity: warning
            component: api
          annotations:
            summary: "Phoenix API high latency"
            description: "Phoenix API p99 latency is above 1 second."
        
        - alert: PhoenixAPIHighErrorRate
          expr: rate(http_requests_total{job="phoenix-api",status=~"5.."}[5m]) > 0.05
          for: 5m
          labels:
            severity: warning
            component: api
          annotations:
            summary: "Phoenix API high error rate"
            description: "Phoenix API error rate is above 5%."
    
    - name: phoenix.experiments
      interval: 60s
      rules:
        - alert: ExperimentStuck
          expr: |
            phoenix_experiment_duration_seconds{status="running"} > 86400
          for: 30m
          labels:
            severity: warning
            component: experiments
          annotations:
            summary: "Experiment running too long"
            description: "Experiment {{ $labels.experiment_id }} has been running for more than 24 hours."
        
        - alert: ExperimentHighFailureRate
          expr: |
            rate(phoenix_experiment_status_transitions_total{to_status="failed"}[1h]) 
            / 
            rate(phoenix_experiment_status_transitions_total{from_status="pending"}[1h]) 
            > 0.2
          for: 15m
          labels:
            severity: warning
            component: experiments
          annotations:
            summary: "High experiment failure rate"
            description: "More than 20% of experiments are failing."
    
    - name: phoenix.collectors
      interval: 30s
      rules:
        - alert: CollectorHighMemoryUsage
          expr: |
            container_memory_usage_bytes{pod=~"phoenix-collector-.*"} 
            / 
            container_spec_memory_limit_bytes{pod=~"phoenix-collector-.*"} 
            > 0.9
          for: 10m
          labels:
            severity: warning
            component: collectors
          annotations:
            summary: "Collector high memory usage"
            description: "Collector {{ $labels.pod }} memory usage is above 90% of limit."
        
        - alert: CollectorHighCPUUsage
          expr: |
            rate(container_cpu_usage_seconds_total{pod=~"phoenix-collector-.*"}[5m]) 
            > 0.8
          for: 10m
          labels:
            severity: warning
            component: collectors
          annotations:
            summary: "Collector high CPU usage"
            description: "Collector {{ $labels.pod }} CPU usage is above 80%."
        
        - alert: CollectorDataLoss
          expr: |
            rate(otelcol_processor_dropped_metric_points[5m]) > 0
          for: 5m
          labels:
            severity: critical
            component: collectors
          annotations:
            summary: "Collector dropping metrics"
            description: "Collector {{ $labels.pod }} is dropping metrics."
    
    - name: phoenix.database
      interval: 30s
      rules:
        - alert: DatabaseConnectionPoolExhausted
          expr: |
            phoenix_database_connections_active 
            / 
            phoenix_database_connections_max 
            > 0.9
          for: 5m
          labels:
            severity: warning
            component: database
          annotations:
            summary: "Database connection pool almost exhausted"
            description: "Database connection pool is above 90% capacity."
        
        - alert: DatabaseSlowQueries
          expr: |
            rate(phoenix_database_query_duration_seconds_bucket{le="1"}[5m]) 
            / 
            rate(phoenix_database_query_duration_seconds_count[5m]) 
            < 0.95
          for: 10m
          labels:
            severity: warning
            component: database
          annotations:
            summary: "Database slow queries"
            description: "More than 5% of database queries are taking longer than 1 second."
{{- end }}