apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phoenix-prod

bases:
  - ../../base

replicas:
  - name: api-gateway
    count: 3
  - name: config-generator
    count: 3
  - name: experiment-controller
    count: 2

patchesStrategicMerge:
  - patches.yaml
  - ingress.yaml

configMapGenerator:
  - name: phoenix-config
    behavior: merge
    literals:
      - log-level=warn
      - enable-tracing=true
      - db-ssl-mode=require

images:
  - name: phoenix/api-gateway
    newName: gcr.io/phoenix-platform/api-gateway
    newTag: v1.0.0
  - name: phoenix/experiment-controller
    newName: gcr.io/phoenix-platform/experiment-controller
    newTag: v1.0.0
  - name: phoenix/config-generator
    newName: gcr.io/phoenix-platform/config-generator
    newTag: v1.0.0
  - name: phoenix/pipeline-operator
    newName: gcr.io/phoenix-platform/pipeline-operator
    newTag: v1.0.0
  - name: phoenix/loadsim-operator
    newName: gcr.io/phoenix-platform/loadsim-operator
    newTag: v1.0.0
  - name: phoenix/dashboard
    newName: gcr.io/phoenix-platform/dashboard
    newTag: v1.0.0