groups:
  - name: phoenix_optimisation_kpis
    rules:
      - record: phoenix:cost_reduction_ratio
        expr: 1 - (sum(phoenix_observer_kpi_store_phoenix_pipeline_output_cardinality_estimate{phoenix_pipeline_label="optimised"}) / ignoring(pipeline_output_type) sum(phoenix_observer_kpi_store_phoenix_pipeline_output_cardinality_estimate{phoenix_pipeline_label="full_fidelity"}))
      
      - record: phoenix:cardinality_delta_percent
        expr: 100 * (sum(phoenix_observer_kpi_store_phoenix_pipeline_output_cardinality_estimate{phoenix_pipeline_label="optimised"}) / ignoring(pipeline_output_type) sum(phoenix_observer_kpi_store_phoenix_pipeline_output_cardinality_estimate{phoenix_pipeline_label="full_fidelity"}) - 1)
      
      - record: phoenix:experimental_savings_potential
        expr: 1 - (sum(phoenix_observer_kpi_store_phoenix_pipeline_output_cardinality_estimate{phoenix_pipeline_label="experimental"}) / ignoring(pipeline_output_type) sum(phoenix_observer_kpi_store_phoenix_pipeline_output_cardinality_estimate{phoenix_pipeline_label="full_fidelity"}))
      
      - record: phoenix:pipeline_health
        expr: sum by (phoenix_pipeline_label) (phoenix_observer_kpi_store_phoenix_pipeline_health{} > 0)
  
  - name: phoenix_alerts
    rules:
      - alert: PhoenixOptimizationDrift
        expr: phoenix:cost_reduction_ratio < 0.4 for 10m
        labels: 
          severity: warning
          team: observability
          component: phoenix
        annotations:
          summary: Phoenix optimized pipeline no longer hitting 40% reduction
          description: "Current cost reduction ratio is {{ $value | printf \"%.2f\" }}. Check pipeline configurations and control loop."
          runbook_url: "https://observability-docs.internal/phoenix/troubleshooting.md#optimization-drift"

      - alert: PhoenixControllerFailure
        expr: absent(timestamp(phoenix_observer_kpi_store_phoenix_controller_heartbeat_timestamp)) > 300
        labels:
          severity: critical
          team: observability
          component: phoenix
        annotations:
          summary: Phoenix controller hasn't updated metrics in 5+ minutes
          description: "The Phoenix controller service appears to be down or unresponsive. Check logs and process status."
          runbook_url: "https://observability-docs.internal/phoenix/troubleshooting.md#controller-failure"
      
      - alert: PhoenixControllerConfigurationFailure
        expr: phoenix_observer_kpi_store_phoenix_controller_config_write_failures_total > 0
        labels:
          severity: critical
          team: observability
          component: phoenix
        annotations:
          summary: Phoenix controller failed to write configuration
          description: "The Phoenix controller has failed to update the configuration file. Check permissions and disk space."
          runbook_url: "https://observability-docs.internal/phoenix/troubleshooting.md#config-write-failures"
      
      - alert: PhoenixExperimentalPipelineUnstable
        expr: sum(phoenix_observer_kpi_store_phoenix_pipeline_health{phoenix_pipeline_label="experimental"}) == 0 and sum(phoenix_observer_kpi_store_phoenix_pipeline_output_cardinality_estimate{phoenix_pipeline_label="experimental"}) > 0
        labels:
          severity: warning
          team: observability
          component: phoenix
        annotations:
          summary: Phoenix experimental pipeline shows processing issues
          description: "The experimental pipeline is enabled but showing health issues. Review logs and metrics."
          runbook_url: "https://observability-docs.internal/phoenix/troubleshooting.md#experimental-pipeline-issues"
