groups:
  - name: phoenix_core_metrics
    interval: 30s
    rules:
      # Signal Preservation Metrics
      - record: phoenix:signal_preservation_score
        expr: |
          1 - (
            sum(rate(otelcol_processor_dropped_metric_points_total[5m])) by (pipeline) / 
            clamp_min(sum(rate(otelcol_receiver_accepted_metric_points_total[5m])) by (pipeline), 1)
          )
        labels:
          metric_type: "efficiency"
          
      - record: phoenix:metric_fidelity_ratio
        expr: |
          sum(rate(otelcol_exporter_sent_metric_points_total[5m])) by (pipeline, exporter) /
          clamp_min(sum(rate(otelcol_receiver_accepted_metric_points_total[5m])) by (pipeline), 1)
        labels:
          metric_type: "fidelity"

      # Cardinality Metrics
      - record: phoenix:cardinality_growth_rate
        expr: |
          deriv(phoenix_observer_kpi_store_phoenix_pipeline_output_cardinality_estimate[5m])
        labels:
          metric_type: "cardinality"
          
      - record: phoenix:cardinality_efficiency_ratio
        expr: |
          phoenix_observer_kpi_store_phoenix_pipeline_output_cardinality_estimate{pipeline="optimized"} /
          clamp_min(phoenix_observer_kpi_store_phoenix_pipeline_output_cardinality_estimate{pipeline="full_fidelity"}, 1)
        labels:
          metric_type: "efficiency"
          
      - record: phoenix:cardinality_reduction_percentage
        expr: |
          100 * (1 - phoenix:cardinality_efficiency_ratio)
        labels:
          metric_type: "efficiency"

      # Resource Utilization Metrics
      - record: phoenix:memory_utilization_percentage
        expr: |
          100 * (
            sum(container_memory_usage_bytes{container=~"otelcol.*"}) by (container) /
            sum(container_spec_memory_limit_bytes{container=~"otelcol.*"}) by (container)
          )
        labels:
          metric_type: "resource"
          
      - record: phoenix:cpu_utilization_percentage
        expr: |
          100 * sum(rate(container_cpu_usage_seconds_total{container=~"otelcol.*"}[5m])) by (container)
        labels:
          metric_type: "resource"
          
      - record: phoenix:resource_efficiency_score
        expr: |
          (phoenix:signal_preservation_score * 100) / 
          clamp_min(phoenix:memory_utilization_percentage + phoenix:cpu_utilization_percentage, 1)
        labels:
          metric_type: "efficiency"

      # Pipeline Performance Metrics
      - record: phoenix:pipeline_latency_p99
        expr: |
          histogram_quantile(0.99, 
            sum(rate(otelcol_processor_batch_timeout_trigger_send_total[5m])) by (pipeline, le)
          )
        labels:
          metric_type: "performance"
          
      - record: phoenix:pipeline_throughput_rate
        expr: |
          sum(rate(otelcol_receiver_accepted_metric_points_total[5m])) by (pipeline)
        labels:
          metric_type: "performance"
          
      - record: phoenix:pipeline_error_rate
        expr: |
          sum(rate(otelcol_exporter_send_failed_metric_points_total[5m])) by (pipeline, exporter) /
          clamp_min(sum(rate(otelcol_exporter_sent_metric_points_total[5m])) by (pipeline, exporter), 1)
        labels:
          metric_type: "reliability"

      # Control Loop Metrics
      - record: phoenix:control_mode_transitions_total
        expr: |
          changes(phoenix_control_optimization_mode[10m])
        labels:
          metric_type: "control"
          
      - record: phoenix:control_stability_score
        expr: |
          1 - (phoenix:control_mode_transitions_total / 6)
        labels:
          metric_type: "control"
          
      - record: phoenix:control_loop_effectiveness
        expr: |
          abs(phoenix_observer_kpi_store_phoenix_pipeline_output_cardinality_estimate{pipeline="optimized"} - 20000) / 20000
        labels:
          metric_type: "control"

  - name: phoenix_advanced_analytics
    interval: 60s
    rules:
      # Anomaly Detection Preparation
      - record: phoenix:cardinality_zscore
        expr: |
          (
            phoenix_observer_kpi_store_phoenix_pipeline_output_cardinality_estimate - 
            avg_over_time(phoenix_observer_kpi_store_phoenix_pipeline_output_cardinality_estimate[1h])
          ) / stddev_over_time(phoenix_observer_kpi_store_phoenix_pipeline_output_cardinality_estimate[1h])
        labels:
          metric_type: "anomaly"
          
      - record: phoenix:cardinality_explosion_risk
        expr: |
          clamp_max(
            phoenix:cardinality_growth_rate / 
            avg_over_time(phoenix:cardinality_growth_rate[30m]), 
            10
          )
        labels:
          metric_type: "anomaly"

      # Cost Efficiency Metrics
      - record: phoenix:cost_per_million_datapoints
        expr: |
          (phoenix:memory_utilization_percentage + phoenix:cpu_utilization_percentage) / 
          (sum(rate(otelcol_receiver_accepted_metric_points_total[5m])) / 1000000)
        labels:
          metric_type: "cost"
          
      - record: phoenix:optimization_savings_percentage
        expr: |
          100 * (1 - (
            sum(phoenix:cost_per_million_datapoints{pipeline="optimized"}) /
            sum(phoenix:cost_per_million_datapoints{pipeline="full_fidelity"})
          ))
        labels:
          metric_type: "cost"

      # SLI/SLO Metrics
      - record: phoenix:sli_data_freshness
        expr: |
          time() - max(prometheus_tsdb_highest_timestamp_seconds) by (pipeline)
        labels:
          metric_type: "sli"
          
      - record: phoenix:sli_availability
        expr: |
          avg_over_time(up{job=~"otelcol.*"}[5m])
        labels:
          metric_type: "sli"
          
      - record: phoenix:slo_compliance
        expr: |
          (phoenix:sli_availability >= 0.999) and
          (phoenix:sli_data_freshness <= 60) and
          (phoenix:signal_preservation_score >= 0.95)
        labels:
          metric_type: "slo"

  - name: phoenix_alerts
    interval: 30s
    rules:
      - alert: PhoenixCardinalityExplosion
        expr: phoenix:cardinality_explosion_risk > 5
        for: 2m
        labels:
          severity: critical
          component: phoenix
        annotations:
          summary: "Cardinality explosion detected in Phoenix pipeline"
          description: "Cardinality growth rate is {{ $value }} times normal (pipeline: {{ $labels.pipeline }})"
          
      - alert: PhoenixPipelineError
        expr: phoenix:pipeline_error_rate > 0.05
        for: 5m
        labels:
          severity: warning
          component: phoenix
        annotations:
          summary: "High error rate in Phoenix pipeline"
          description: "Pipeline {{ $labels.pipeline }} has {{ $value | humanizePercentage }} error rate"
          
      - alert: PhoenixResourceExhaustion
        expr: phoenix:memory_utilization_percentage > 90
        for: 5m
        labels:
          severity: critical
          component: phoenix
        annotations:
          summary: "Phoenix collector memory exhaustion"
          description: "Container {{ $labels.container }} is using {{ $value }}% of memory limit"
          
      - alert: PhoenixControlLoopInstability
        expr: phoenix:control_stability_score < 0.5
        for: 10m
        labels:
          severity: warning
          component: phoenix
        annotations:
          summary: "Phoenix control loop is unstable"
          description: "Control loop stability score is {{ $value }}, indicating frequent mode changes"
          
      - alert: PhoenixSLOViolation
        expr: phoenix:slo_compliance == 0
        for: 5m
        labels:
          severity: critical
          component: phoenix
        annotations:
          summary: "Phoenix SLO violation detected"
          description: "One or more SLOs are not being met for pipeline {{ $labels.pipeline }}"