apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phoenix-system

resources:
  - namespace.yaml
  - rbac.yaml
  - secrets.yaml
  - configmaps.yaml
  - network-policies.yaml

commonLabels:
  app.kubernetes.io/name: phoenix
  app.kubernetes.io/part-of: phoenix-platform

images:
  - name: phoenix/phoenix-api
    newTag: latest
  - name: phoenix/phoenix-agent
    newTag: latest