{{- if .Values.loadsimOperator.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "phoenix.loadsimOperatorServiceAccountName" . }}
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
    app.kubernetes.io/component: loadsim-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "phoenix.fullname" . }}-loadsim-operator
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
    app.kubernetes.io/component: loadsim-operator
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - phoenix.newrelic.com
    resources:
      - loadsimulationjobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - phoenix.newrelic.com
    resources:
      - loadsimulationjobs/finalizers
    verbs:
      - update
  - apiGroups:
      - phoenix.newrelic.com
    resources:
      - loadsimulationjobs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "phoenix.fullname" . }}-loadsim-operator
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
    app.kubernetes.io/component: loadsim-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "phoenix.fullname" . }}-loadsim-operator
subjects:
  - kind: ServiceAccount
    name: {{ include "phoenix.loadsimOperatorServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "phoenix.fullname" . }}-loadsim-operator-leader-election
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
    app.kubernetes.io/component: loadsim-operator
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "phoenix.fullname" . }}-loadsim-operator-leader-election
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
    app.kubernetes.io/component: loadsim-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "phoenix.fullname" . }}-loadsim-operator-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "phoenix.loadsimOperatorServiceAccountName" . }}
{{- end }}