apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: phoenix-platform
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
    - port: 8081
      targetPort: metrics
      name: metrics
  selector:
    app.kubernetes.io/name: api
