mode: moderate
last_updated: '2025-05-22T07:10:03.857421+00:00'
reason: "Mode change: adaptive \u2192 moderate (cardinality: 189)"
ts_count: 189
config_version: 1747897803
correlation_id: observer-1747897803
optimization_level: 0
thresholds:
  moderate: 300.0
  adaptive: 375.0
  ultra: 450.0
state:
  previous_mode: adaptive
  transition_timestamp: '2025-05-22T07:10:03.857421+00:00'
  transition_duration_seconds: 0
  stability_period_seconds: 300
  mode_changes_total: 5
observer_metadata:
  cardinality_analysis:
    total_phoenix_metrics: 189
    unique_time_series: 189
    reduction_potential: 0 series
    sample_metrics:
    - phoenix_full_process_system_cpu_time_seconds_total#cpu="cpu9",focus="process",job="phoenix-synthetic-generator",phoenix_cardinality_tier="process-focused",phoenix_priority="high",pipeline="full",state="wait"
    - phoenix_full_process_system_cpu_time_seconds_total#cpu="cpu1",focus="process",phoenix_cardinality_tier="process-focused",phoenix_priority="high",pipeline="full",state="nice"
    - phoenix_full_process_system_cpu_time_seconds_total#cpu="cpu8",focus="process",job="phoenix-synthetic-generator",phoenix_cardinality_tier="process-focused",phoenix_priority="high",pipeline="full",state="nice"
    - phoenix_full_process_system_cpu_time_seconds_total#cpu="cpu0",focus="process",phoenix_cardinality_tier="process-focused",phoenix_priority="high",pipeline="full",state="wait"
    - phoenix_full_process_system_cpu_time_seconds_total#cpu="cpu1",focus="process",job="phoenix-synthetic-generator",phoenix_cardinality_tier="process-focused",phoenix_priority="high",pipeline="full",state="steal"
