# Optimization mode template file with improved synchronization
# Enhanced with version tracking and correlation IDs for coherent state transitions

# Mode configuration
mode: moderate

# Metadata
last_updated: "2025-05-22T00:00:00Z"
reason: "initial_state"
ts_count: 0
config_version: 1
correlation_id: "init-00000000-0000-0000-0000-000000000000"

# Optimization level (0-100)
optimization_level: 0

# Current thresholds (graduated levels)
thresholds:
  moderate: 300.0
  caution: 350.0
  warning: 400.0
  ultra: 450.0

# State transition information
state:
  previous_mode: "initial"
  transition_timestamp: "2025-05-22T00:00:00Z"
  transition_duration_seconds: 0
  stability_period_seconds: 300  # Don't change mode again for 5 minutes