# Optimization mode control file with enhanced structure
# This file is read by otelcol-main and written by otelcol-observer
# Changes trigger pipeline configuration updates

# Mode configuration - determines active pipeline optimization level
mode: "moderate"

# Metadata for tracking and coordination
last_updated: "2025-05-22T20:00:00Z"
reason: "schema_alignment"
ts_count: 0
config_version: 1
correlation_id: "init-phoenix-vnext-1747946400"

# Fine-grained optimization level (0-100)
# 0-25: moderate, 26-75: adaptive, 76-100: ultra
optimization_level: 0

# Current thresholds (aligned with otelcol-main schema)
thresholds:
  moderate: 300.0
  adaptive: 375.0
  ultra: 450.0

# State transition information for debugging and audit
state:
  previous_mode: "initial"
  transition_timestamp: "2025-05-22T20:00:00Z"
  transition_duration_seconds: 0
  stability_period_seconds: 300  # Don't change mode again for 5 minutes