# Phoenix Prometheus Configuration
# Scrapes metrics from Phoenix Platform services

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'phoenix-dev'
    environment: 'development'

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Phoenix API - Control plane metrics
  - job_name: 'phoenix-api'
    static_configs:
      - targets: ['phoenix-api:8081']
    metrics_path: /metrics
    scrape_interval: 15s

  # Pushgateway - Metrics from Phoenix Agents
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
    honor_labels: true
    scrape_interval: 15s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Grafana metrics (optional)
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s

  # Redis metrics (optional)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

# Remote write configuration (optional)
# remote_write:
#   - url: "http://remote-prometheus:9090/api/v1/write"
#     write_relabel_configs:
#       - source_labels: [__name__]
#         regex: 'phoenix_.*'
#         action: keep