# Phoenix Platform Prometheus Configuration
# This is the main configuration for development environment
# For production, use configs/generated/production/prometheus.yaml

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'phoenix-dev'
    environment: 'development'
    architecture: 'lean'

# Rule files
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Phoenix API metrics
  - job_name: 'phoenix-api'
    static_configs:
      - targets: ['phoenix-api:8081', 'localhost:8081']
    metrics_path: /metrics

  # Pushgateway for agent metrics
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091', 'localhost:9091']
    metric_relabel_configs:
      # Preserve important labels
      - source_labels: [experiment_id]
        target_label: experiment_id
      - source_labels: [variant]
        target_label: variant  
      - source_labels: [host]
        target_label: host
      - source_labels: [pipeline_id]
        target_label: pipeline_id

  # Grafana metrics (if available)
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics