apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: phoenix-system
  labels:
    app: prometheus
    component: monitoring
data:
  prometheus.yml: |
    # Phoenix Platform Prometheus Configuration
    # This configuration is managed via configs/monitoring/prometheus/prometheus.yml
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        cluster: 'phoenix-k8s'
        environment: 'production'
        architecture: 'lean'

    # Rule files
    rule_files:
      - "/etc/prometheus/rules/*.yml"

    # Alerting configuration
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - 'alertmanager:9093'

    # Scrape configurations
    scrape_configs:
      # Prometheus self-monitoring
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # Phoenix API metrics
      - job_name: 'phoenix-api'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - phoenix-system
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: phoenix-api
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
        metrics_path: /metrics

      # Pushgateway for agent metrics
      - job_name: 'pushgateway'
        honor_labels: true
        static_configs:
          - targets: ['prometheus-pushgateway:9091']
        metric_relabel_configs:
          # Preserve important labels
          - source_labels: [experiment_id]
            target_label: experiment_id
          - source_labels: [variant]
            target_label: variant  
          - source_labels: [host]
            target_label: host
          - source_labels: [pipeline_id]
            target_label: pipeline_id

      # Phoenix Agents (direct scraping via service discovery)
      - job_name: 'phoenix-agents'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - phoenix-system
                - default
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: phoenix-agent
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_host_ip]
            target_label: host
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace

      # Grafana metrics
      - job_name: 'grafana'
        static_configs:
          - targets: ['grafana:3000']
        metrics_path: /metrics