# Phoenix v3 Ultimate Process-Metrics Stack - Main OTel Collector Configuration
# Simplified version for demo - focused on synthetic metrics

receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
      grpc:
        endpoint: "0.0.0.0:4317"

processors:
  batch:
    send_batch_size: 8192
    timeout: 10s

  resourcedetection:
    detectors: [system, env]
    system:
      hostname_sources: ["os"]

  resource/full:
    attributes:
      - key: phoenix.pipeline.strategy
        value: "full_fidelity"
        action: upsert

  resource/optimized:
    attributes:
      - key: phoenix.pipeline.strategy
        value: "optimized"
        action: upsert

  resource/experimental:
    attributes:
      - key: phoenix.pipeline.strategy
        value: "experimental"
        action: upsert

  # Cardinality reduction for optimized pipeline - keep some important attributes
  groupbyattrs/optimized:
    keys:
      - host_name
      - service_name
      - process_executable_name
      - custom_service_tier_simulated
      - phoenix_pipeline_strategy

  # Aggressive cardinality reduction for experimental pipeline - minimal attributes
  groupbyattrs/experimental:
    keys:
      - service_name
      - process_executable_name
      - phoenix_pipeline_strategy

exporters:
  prometheus/full:
    endpoint: "0.0.0.0:8888"
    namespace: "phoenix_full_final_output"
    resource_to_telemetry_conversion:
      enabled: true
    send_timestamps: true

  prometheus/optimized:
    endpoint: "0.0.0.0:8889"
    namespace: "phoenix_opt_final_output"
    resource_to_telemetry_conversion:
      enabled: true
    send_timestamps: true

  prometheus/experimental:
    endpoint: "0.0.0.0:8890"
    namespace: "phoenix_exp_final_output"
    resource_to_telemetry_conversion:
      enabled: true
    send_timestamps: true

  logging:
    verbosity: basic

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
  pprof:
    endpoint: "0.0.0.0:1777"
  zpages:
    endpoint: "0.0.0.0:55679"
  memory_ballast:
    size_mib: 640

service:
  extensions: [health_check, pprof, zpages, memory_ballast]
  telemetry:
    metrics:
      address: ":8887"
      level: detailed
    logs:
      level: info

  pipelines:
    metrics/full:
      receivers: [otlp]
      processors: [resourcedetection, resource/full, batch]
      exporters: [prometheus/full, logging]

    metrics/optimized:
      receivers: [otlp]
      processors: [resourcedetection, resource/optimized, groupbyattrs/optimized, batch]
      exporters: [prometheus/optimized]

    metrics/experimental:
      receivers: [otlp]
      processors: [resourcedetection, resource/experimental, groupbyattrs/experimental, batch]
      exporters: [prometheus/experimental]
