apiVersion: apps/v1
kind: Deployment
metadata:
  name: experiment-controller
  namespace: phoenix-system
  labels:
    app.kubernetes.io/name: experiment-controller
    app.kubernetes.io/component: control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: experiment-controller
      app.kubernetes.io/component: control-plane
  template:
    metadata:
      labels:
        app.kubernetes.io/name: experiment-controller
        app.kubernetes.io/component: control-plane
    spec:
      serviceAccountName: experiment-controller
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: controller
        image: phoenix/experiment-controller:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: grpc
          containerPort: 50051
          protocol: TCP
        - name: metrics
          containerPort: 8081
          protocol: TCP
        - name: health
          containerPort: 8082
          protocol: TCP
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "phoenix"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: phoenix-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: phoenix-db-credentials
              key: password
        - name: GENERATOR_ADDR
          value: "config-generator:50052"
        - name: RECONCILE_INTERVAL
          value: "30s"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 10
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: experiment-controller
  namespace: phoenix-system
  labels:
    app.kubernetes.io/name: experiment-controller
    app.kubernetes.io/component: control-plane
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 50051
    targetPort: grpc
    protocol: TCP
  - name: metrics
    port: 8081
    targetPort: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: experiment-controller
    app.kubernetes.io/component: control-plane
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: experiment-controller
  namespace: phoenix-system
  labels:
    app.kubernetes.io/name: experiment-controller
    app.kubernetes.io/component: control-plane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: experiment-controller
rules:
- apiGroups: ["phoenix.io"]
  resources: ["experiments", "experiments/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: experiment-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: experiment-controller
subjects:
- kind: ServiceAccount
  name: experiment-controller
  namespace: phoenix-system