apiVersion: v1
kind: Secret
metadata:
  name: phoenix-secrets
  namespace: phoenix-system
  labels:
    app.kubernetes.io/name: phoenix
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  jwt-secret: "CHANGE_THIS_IN_PRODUCTION_USE_STRONG_RANDOM_VALUE"
---
apiVersion: v1
kind: Secret
metadata:
  name: phoenix-db-credentials
  namespace: phoenix-system
  labels:
    app.kubernetes.io/name: phoenix
    app.kubernetes.io/component: database
type: Opaque
stringData:
  username: "phoenix"
  password: "CHANGE_THIS_IN_PRODUCTION"
  database: "phoenix"
---
apiVersion: v1
kind: Secret
metadata:
  name: phoenix-tls
  namespace: phoenix-system
  labels:
    app.kubernetes.io/name: phoenix
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  # Placeholder for TLS certificate and key
  # Generate real certificates for production
  tls.crt: ""
  tls.key: ""