apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy # Browser should access Grafana, Grafana server accesses Prometheus
    url: http://prometheus:9090 # Prometheus URL from Grafana container's perspective
    uid: prometheus # Important - explicit UID to match dashboard references
    isDefault: true
    jsonData:
      timeInterval: "15s" # Default scrape interval hint