apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy # Browser should access Grafana, Grafana server accesses Prometheus
    url: http://prometheus:9090 # Prometheus URL from Grafana container's perspective
    isDefault: true
    jsonData:
      timeInterval: "15s" # Default scrape interval hint