apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  labels:
    app.kubernetes.io/name: ${SERVICE_NAME}
    app.kubernetes.io/part-of: phoenix-platform
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
  - port: ${HTTP_PORT}
    targetPort: http
    protocol: TCP
    name: http
  - port: ${METRICS_PORT}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: ${SERVICE_NAME}
