apiVersion: v1
kind: ConfigMap
metadata:
  name: control-actuator-script
data:
  update-control.sh: |
    #!/bin/bash
    set -euo pipefail

    # Environment variables
    PROMETHEUS_URL="${PROMETHEUS_URL:-http://prometheus:9090}"
    CONTROL_FILE="/config/optimization_mode.yaml"
    INTERVAL="${ADAPTIVE_CONTROLLER_INTERVAL_SECONDS:-60}"
    
    # Thresholds
    CONSERVATIVE_MAX="${THRESHOLD_OPTIMIZATION_CONSERVATIVE_MAX_TS:-15000}"
    AGGRESSIVE_MIN="${THRESHOLD_OPTIMIZATION_AGGRESSIVE_MIN_TS:-25000}"
    
    while true; do
      echo "[$(date)] Checking pipeline metrics..."
      
      # Query current cardinality
      QUERY='sum(phoenix_observer_kpi_store_phoenix_pipeline_output_cardinality_estimate{pipeline="metrics/optimised"})'
      RESPONSE=$(curl -s "${PROMETHEUS_URL}/api/v1/query?query=${QUERY}")
      
      if [ $? -eq 0 ]; then
        CARDINALITY=$(echo "$RESPONSE" | jq -r '.data.result[0].value[1] // "0"')
        echo "[$(date)] Current cardinality: $CARDINALITY"
        
        # Determine optimization mode
        if (( $(echo "$CARDINALITY < $CONSERVATIVE_MAX" | bc -l) )); then
          MODE="conservative"
        elif (( $(echo "$CARDINALITY > $AGGRESSIVE_MIN" | bc -l) )); then
          MODE="aggressive"
        else
          MODE="balanced"
        fi
        
        echo "[$(date)] Setting optimization mode to: $MODE"
        
        # Update control file
        cat > "$CONTROL_FILE" << EOF
    optimization_mode: $MODE
    last_updated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
    current_cardinality: $CARDINALITY
    thresholds:
      conservative_max: $CONSERVATIVE_MAX
      aggressive_min: $AGGRESSIVE_MIN
    EOF
      else
        echo "[$(date)] Error querying Prometheus"
      fi
      
      sleep "$INTERVAL"
    done

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phoenix-control-config
data:
  optimization_mode.yaml: |
    optimization_mode: balanced
    last_updated: "2024-01-01T00:00:00Z"
    current_cardinality: 0
    thresholds:
      conservative_max: 15000
      aggressive_min: 25000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-actuator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-actuator
  template:
    metadata:
      labels:
        app: control-actuator
        component: control
    spec:
      containers:
      - name: actuator
        image: alpine:latest
        command: ["/bin/sh"]
        args: ["/scripts/update-control.sh"]
        env:
        - name: PROMETHEUS_URL
          value: "http://prometheus:9090"
        - name: ADAPTIVE_CONTROLLER_INTERVAL_SECONDS
          value: "60"
        - name: THRESHOLD_OPTIMIZATION_CONSERVATIVE_MAX_TS
          value: "15000"
        - name: THRESHOLD_OPTIMIZATION_AGGRESSIVE_MIN_TS
          value: "25000"
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
          requests:
            memory: 64Mi
            cpu: 50m
        volumeMounts:
        - name: script
          mountPath: /scripts
        - name: control-config
          mountPath: /config
      volumes:
      - name: script
        configMap:
          name: control-actuator-script
          defaultMode: 0755
      - name: control-config
        configMap:
          name: phoenix-control-config