apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-observer-config
data:
  config.yaml: |
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector-main'
              scrape_interval: 15s
              static_configs:
                - targets: ['otel-collector-main:8888']

    processors:
      batch:
        send_batch_size: 1000
        timeout: 5s

    exporters:
      prometheus:
        endpoint: "0.0.0.0:9888"
        resource_to_telemetry_conversion:
          enabled: true

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch]
          exporters: [prometheus]

      telemetry:
        logs:
          level: info
        metrics:
          level: detailed
          address: 0.0.0.0:8888

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector-observer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector-observer
  template:
    metadata:
      labels:
        app: otel-collector-observer
        component: observer
    spec:
      serviceAccountName: otel-collector
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.91.0
        args:
          - --config=/etc/otel-collector/config.yaml
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 250m
        ports:
        - containerPort: 9888  # Prometheus metrics
          name: metrics
        - containerPort: 13134 # Health check
          name: health
        volumeMounts:
        - name: config
          mountPath: /etc/otel-collector
        livenessProbe:
          httpGet:
            path: /
            port: 13134
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 13134
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: otel-collector-observer-config

---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-observer
spec:
  selector:
    app: otel-collector-observer
  ports:
  - name: metrics
    port: 9888
    targetPort: 9888