name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-pr:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check commit messages
        run: |
          # Get all commits in the PR
          commits=$(git log --format=%s origin/${{ github.base_ref }}..HEAD)
          
          # Check each commit message
          while IFS= read -r commit; do
            if [[ ! "$commit" =~ ^(feat|fix|docs|style|refactor|test|chore|perf|ci|build|revert)(\(.+\))?: ]]; then
              echo "Invalid commit message: $commit"
              echo "Commit messages must follow conventional commits format"
              exit 1
            fi
          done <<< "$commits"

      - name: Check file changes
        run: |
          # Check for large files
          large_files=$(find . -type f -size +10M | grep -v .git || true)
          if [ -n "$large_files" ]; then
            echo "Large files detected (>10MB):"
            echo "$large_files"
            exit 1
          fi
          
          # Check for sensitive files
          sensitive_patterns=".env|.pem|.key|password|secret"
          sensitive_files=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -E "$sensitive_patterns" || true)
          if [ -n "$sensitive_files" ]; then
            echo "Potentially sensitive files detected:"
            echo "$sensitive_files"
            exit 1
          fi

  size-check:
    name: Bundle Size Check
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'frontend')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: dashboard/package-lock.json

      - name: Install dependencies
        run: cd dashboard && npm ci

      - name: Build dashboard
        run: cd dashboard && npm run build

      - name: Check bundle size
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: dashboard

  label-pr:
    name: Auto Label PR
    runs-on: ubuntu-latest
    steps:
      - name: Label PR based on files
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml